### ISSUE TITLE
Broken links in manifest

### ISSUE THREAD

**Issue by berezovskyi** [rubenmv/extension-goodreads-ratings-for-amazon#1]
<img width="911" alt="image" src="https://cloud.githubusercontent.com/assets/64734/21698522/a60d0602-d397-11e6-950b-3ab08425e8c6.png">

Correct link is https://github.com/rubenmv/extension-goodreads-ratings-for-amazon/

**Comment by rubenmv** [comment]
Thank you for the heads up. Fixed now but it's in revision process by Mozilla, it will be published soon.
