### ISSUE TITLE
Goodreads has changed and possibly broke link to Amazon

### ISSUE THREAD

**Issue by llba5313** [rubenmv/extension-goodreads-ratings-for-amazon#13]
Goodreads has changed their format and possibly broken the link you use to display the Goodreads ratings on a Amazon page. It has stopped working for me in the USA.

Thanks - love this extension!

**Comment by rubenmv** [comment]
Hi, I just updated the extension for Chrome, Edge version is still in review, but it shouldn't take much longer.

I'm closing this issue, if it's still not working please open a new issue and provide some examples. 
Thank you.
