### ISSUE TITLE
doesn't seem to work anymore

### ISSUE THREAD

**Issue by ghosttie** [rubenmv/extension-goodreads-ratings-for-amazon#14]
I haven't seen the Goodreads rating on an Amazon book page in a while

**Comment by rubenmv** [comment]
Hi, seems to be working fine for me.. Can you show me some examples?

**Comment by ghosttie** [comment]
The pages I noticed it on today were https://www.amazon.com/gp/product/B06VXWPMV5 and https://www.amazon.com/gp/product/B00V37BC60

**Comment by rubenmv** [comment]
What is your browser? It works fine for me on Chrome, Edge and Firefox.

<img src="https://user-images.githubusercontent.com/64125/129053879-3f154a42-946a-4c25-ba02-6c2edc28f486.png" width="600">

Go to "Manage extensions" in Chrome or the equivalent for Edge or the browser you are using and check if the extension is actually enabled. The latest version is 1.8.0 (1.7.5 on Firefox).

**Comment by ghosttie** [comment]
Oh sorry, looks like Chrome had disabled it without me noticing
![image](https://user-images.githubusercontent.com/1552778/129056239-87e16895-4761-4215-9a67-f894ff85e24a.png)
