### ISSUE TITLE
Seems broken now.

### ISSUE THREAD

**Issue by drod3763** [rubenmv/extension-goodreads-ratings-for-amazon#16]
GoodReads has appeared to undergo a redesign and now the extension doesn't appear to work. It used to show Goodreads ratings on the Amazon page but doesn't anymore.

**Comment by berezovskyi** [comment]
Nope, seems to work perfectly:

![image](https://user-images.githubusercontent.com/64734/134750695-2862d417-0adf-4f77-90ad-d3eb75ebe200.png)

Most likely it's some Amazon A/B page tests.
