### ISSUE TITLE
Amazon.com.br

### ISSUE THREAD

**Issue by DyeffersonAz** [rubenmv/extension-goodreads-ratings-for-amazon#17]
Not working in amazon.com.br

**Comment by rubenmv** [comment]
Hi, I've tested some pages and it seems to be working fine, can you post some examples?

**Comment by DyeffersonAz** [comment]
Here is an example [(link)](https://www.amazon.com.br/Il%C3%ADada-Homero/dp/8563560565/ref=sr_1_3?__mk_pt_BR=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=31HX6RNWF5XF6&keywords=Il%C3%ADada&qid=1644950939&s=books&sprefix=il%C3%ADada%2Cstripbooks%2C194&sr=1-3):

![](https://i.imgur.com/UrUT70T.png)

**Comment by DyeffersonAz** [comment]
A book in English [(link)](https://www.amazon.com.br/Odyssey-Homer/dp/0140268863/ref=sr_1_1?__mk_pt_BR=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=1I9FQUN0IYA18&keywords=Oddysey&qid=1644951285&s=books&sprefix=oddysey%2Cstripbooks%2C221&sr=1-1&ufe=app_do%3Aamzn1.fos.6121c6c4-c969-43ae-92f7-cc248fc6181d):

![](https://i.imgur.com/NizE8uF.png)

**Comment by rubenmv** [comment]
Seems to be working fine for both examples:
<img src="https://user-images.githubusercontent.com/64125/154141366-19290425-d3c3-4167-a4aa-ade0b184d006.png" width="400" />


What is that other extension you are using? The one for the "Add book" button, that might be interfering with my extension, try disabling it and let me know if that's the problem.

**Comment by DyeffersonAz** [comment]
> Seems to be working fine for both examples: (image)
> 
> What is that other extension you are using? The one for the "Add book" button, that might be interfering with my extension, try disabling it and let me know if that's the problem.

Disabling it doesn't do anything. That is a userscript.

![](https://i.imgur.com/a81F6LD.png)

**Comment by DyeffersonAz** [comment]
Additional detail: I'm using Mozilla Firefox's version.

**Comment by rubenmv** [comment]
I just submitted a new version for Firefox. It wasn't on par with the other browsers. It might take a few days to be approved.

**Comment by rubenmv** [comment]
Well, that was fast, it just got updated in the store and It seems to be working fine now.
I'm gonna close this issue now. Thank you for letting me know.
