### ISSUE TITLE
Goodreads rating appears, but there's no clickable link to the Goodreads page

### ISSUE THREAD

**Issue by garyking** [rubenmv/extension-goodreads-ratings-for-amazon#19]
Since perhaps a few weeks ago, the Goodratings rating still appears on an Amazon book page, but there's no longer a clickable link to the Goodreads page. 

As seen in the below screenshot:

![Goodreads linked from Amazon book page](https://github.com/rubenmv/extension-goodreads-ratings-for-amazon/assets/343940/14f764ee-f151-4aab-950c-9d1eeabacf1d)

**Comment by berezovskyi** [comment]
Just tested and indeed amazon.com has an unclickable output on Firefox. The output is not visible at all on amazon.de or amazon.se on Firefox (extension v1.8.0).

On Chrome (extension v2.0.1), I get the same story. Also noticed that if I am logged out of Amazon on amazon.com, I don't see any rating.

**Comment by rubenmv** [comment]
Hi, I just submitted a new version for Chrome and Edge that should fix the problem. It's in review right now, it can take a while to get published (let's hope it doesn't).
Unfortunately For Firefox it's going to take me longer.

Also, what you see in that screenshot, the ratings in plaint text, is not from my extension, that's from Amazon itself. 
[](https://bookriot.com/goodreads-ratings-on-amazon-listings/)

With the new update (version 2.0.3) it should be working again and that text from Amazon will be hidden by default.

Thank you, I'm closing this issue now.
