### ISSUE TITLE
Not Showing

### ISSUE THREAD

**Issue by SirGryphin** [rubenmv/extension-goodreads-ratings-for-amazon#20]
For the past day or so, the chrome extension is no longer working doesn't show for any book. I don't know if amazon changed something on site layout or it goodreads doing.

**Comment by rubenmv** [comment]
Hi, yes, Amazon have been making changes lately, I have submitted a new version with many fixes, it's in review process, it can take a while to be published. More details here:
https://github.com/rubenmv/extension-goodreads-ratings-for-amazon/issues/19#issuecomment-1627449879

Thank you, I'm closing this.
