### ISSUE TITLE
Broken with new Amazon layout

### ISSUE THREAD

**Issue by romanovzky** [rubenmv/extension-goodreads-ratings-for-amazon#4]
Hi Ruben,

Just to let you know that this is now broken as Amazon (at least UK) is now using the US layout for books

![screenshot from 2018-09-17 11-11-25](https://user-images.githubusercontent.com/7794475/45617519-80806d00-ba6a-11e8-83d2-b8f8acd795e3.png)

Cheers!

**Comment by rubenmv** [comment]
Hi! thanks for the heads up, I'm uploading a quick fix tonight, i also added more methods for retrieving the book isbn.

**Comment by romanovzky** [comment]
Fixed!
