### ISSUE TITLE
Amazon audible support

### ISSUE THREAD

**Issue by harshid86** [rubenmv/extension-goodreads-ratings-for-amazon#6]
Please add support for audible domains

**Comment by rubenmv** [comment]
Hi! the extension already works with Audible, this book for example
https://www.audible.com/pd/Stamped-from-the-Beginning-Audiobook/B01N27TTT3
takes a bit to load but it works. That doesn't mean it will work for every book, only if the ISBN or ASIN numbers are properly registered in Goodreads.
