### ISSUE TITLE
Looks like this is not working on Amazon using Firefox

### ISSUE THREAD

**Issue by dddddanny** [rubenmv/extension-goodreads-ratings-for-amazon#7]
This works fine in Chrome, but Firefox does not show when opening an Amazon book page... though if you open an Audible page in Firefox, it's working fine. 

Firefox - v75.0

Tested on both Mac and Windows machines.

**Comment by genekaufman** [comment]
It's failing for me now in Chrome on Windows10 (Sorry, I don't have version info at the moment)
and 
Chromium Linux Mint. Version 79.0.3945.79 (Official Build) Built on Ubuntu , running on LinuxMint 19.3 (64-bit)

**Comment by rubenmv** [comment]
Hi, it seems like Amazon was messing up again with the product pages and some books were failing detection. A new version is uploaded and pending revision by Google.

**Comment by genekaufman** [comment]
Really appreciate the quick action - love this extension, thank you!
