### ISSUE TITLE
broken: hasnt been working for a while now

### ISSUE THREAD

**Issue by makethingsbetter** [rubenmv/extension-goodreads-ratings-for-amazon#9]
broken: hasnt been working for a while now

**Comment by berezovskyi** [comment]
<img width="695" alt="image" src="https://user-images.githubusercontent.com/64734/99197176-102c1e00-2791-11eb-8310-f572fbfb9638.png">

that's right now on Amazon Germany.

**Comment by rubenmv** [comment]
Hi, I'm closing this. I just updated the extension in Chrome, should be working better now. The Edge version is still in review.
If it is still not working please open a new issue and provide some examples.
